In [1]:
import numpy as np

In [2]:
def maxRowIndex(columnIndex, A):
    max = 0
    pos = 0
    for i in range(columnIndex,n):
        if(np.abs(A[i][columnIndex]) > max):
            max = np.abs(A[i][columnIndex])
            pos = i
    return pos

def GuassianEliminationForRow(curr, A):
    # 1.选列主元
    pos = maxRowIndex(curr, A)
    # 2.换行
    tmp = np.copy(A[pos])
    A[pos] = A[curr]
    A[curr] = tmp
    # 3.消元
    for i in range(curr+1, n):
        factor = A[i][curr] / A[curr][curr]
        A[i] -= factor * A[curr]

In [3]:
A1 = np.array([[3.01,6.03,1.99],[1.27,4.16,-1.23],[0.987,-4.81,9.34]])
b1 = np.array([1.0,1.0,1.0])
n = A1.shape[0]
b1 = b1.reshape(n,1)
compose = np.hstack((A1,b1))
print("原方程为：")
print(compose)
# 选列主元的高斯消去法
for i in range(0, n):
    GuassianEliminationForRow(i, compose)
    print("第{}步高斯消去法计算得到的矩阵：".format(i+1))
    print(compose)
# 回代解方程
x = np.zeros(n)
x[n-1] = compose[n-1][n] / compose[n-1][n-1]
for i in range(n-2, -1, -1):
    sum = 0
    for j in range(n-1, i, -1):
        sum += compose[i][j] * x[j]
    x[i] = (compose[i][n]-sum) / compose[i][i]
print("最终求得的解为：{}".format(x))

原方程为：
[[ 3.01   6.03   1.99   1.   ]
 [ 1.27   4.16  -1.23   1.   ]
 [ 0.987 -4.81   9.34   1.   ]]
第1步高斯消去法计算得到的矩阵：
[[ 3.01        6.03        1.99        1.        ]
 [ 0.          1.61578073 -2.06963455  0.57807309]
 [ 0.         -6.78727907  8.68746512  0.67209302]]
第2步高斯消去法计算得到的矩阵：
[[ 3.01000000e+00  6.03000000e+00  1.99000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -6.78727907e+00  8.68746512e+00  6.72093023e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.49522925e-03  7.38071661e-01]]
第3步高斯消去法计算得到的矩阵：
[[ 3.01000000e+00  6.03000000e+00  1.99000000e+00  1.00000000e+00]
 [ 0.00000000e+00 -6.78727907e+00  8.68746512e+00  6.72093023e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.49522925e-03  7.38071661e-01]]
最终求得的解为：[1592.59962484 -631.9113762  -493.61772476]


In [4]:
A2 = np.array([[3.00,6.03,1.99],[1.27,4.16,-1.23],[0.990,-4.81,9.34]])
b2 = np.array([1.0,1.0,1.0])
n = A2.shape[0]
b2 = b2.reshape(n,1)
compose = np.hstack((A2,b2))
print("原方程为：")
print(compose)
# 选列主元的高斯消去法
for i in range(0, n):
    GuassianEliminationForRow(i, compose)
    print("第{}步高斯消去法计算得到的矩阵：".format(i+1))
    print(compose)
# 回代解方程
x = np.zeros(n)
x[n-1] = compose[n-1][n] / compose[n-1][n-1]
for i in range(n-2, -1, -1):
    sum = 0
    for j in range(n-1, i, -1):
        sum += compose[i][j] * x[j]
    x[i] = (compose[i][n]-sum) / compose[i][i]
print("最终求得的解为：{}".format(x))

原方程为：
[[ 3.    6.03  1.99  1.  ]
 [ 1.27  4.16 -1.23  1.  ]
 [ 0.99 -4.81  9.34  1.  ]]
第1步高斯消去法计算得到的矩阵：
[[ 3.          6.03        1.99        1.        ]
 [ 0.          1.6073     -2.07243333  0.57666667]
 [ 0.         -6.7999      8.6833      0.67      ]]
第2步高斯消去法计算得到的矩阵：
[[ 3.          6.03        1.99        1.        ]
 [ 0.         -6.7999      8.6833      0.67      ]
 [ 0.          0.         -0.01995196  0.73503532]]
第3步高斯消去法计算得到的矩阵：
[[ 3.          6.03        1.99        1.        ]
 [ 0.         -6.7999      8.6833      0.67      ]
 [ 0.          0.         -0.01995196  0.73503532]]
最终求得的解为：[119.52733813 -47.14260443 -36.84025611]
